### ISSUE TITLE
Does creating a role and adding it to ansible-galaxy make sense?

### ISSUE THREAD

**Issue by aelsabbahy** [indusbox/goss-ansible#5]
Wondering if it also makes sense to encapsulate this in a role to make it easier for consumption.

Abstract away the whole download, copy (or download) YAML file, and maybe optionally pull back result files

Awesome module :)

**Comment by mcorbin** [comment]
I think (maybe i'm wrong) ansible-galaxy can only share roles and not modules (which goss.py is). But i can add an example role using the goss module in ansible-galaxy (it won't change the installation process of the goss.py file).

**Comment by aelsabbahy** [comment]
Wonder if something like this would work, I haven't pushed anything out to ansible-galaxy before.
https://docs.ansible.com/ansible/playbooks_roles.html#embedding-modules-in-roles

**Comment by mcorbin** [comment]
why not, i will look at this next week.

**Comment by mcorbin** [comment]
A bit late, but i created the role in ansible galaxy : https://galaxy.ansible.com/mcorbin/goss-module/
I will add it to the readme soon.

**Comment by aelsabbahy** [comment]
Nice, thanks for doing this.
